version: '3.1'

services:

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hungbn
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: hungbn
      MYSQL_PASSWORD: hungbn
    ports:
      - "3306:3306"
      - "33060:33060"