export const SECOND = 1000
export const MINUTE = SECOND * 60
export const MINUTE3 = MINUTE * 3
export const MINUTE5 = MINUTE * 5
export const MINUTE15 = MINUTE * 15
export const MINUTE30 = MINUTE * 30
export const HOUR = MINUTE * 60
export const HOUR4 = HOUR * 4
export const HOUR12 = HOUR * 12
export const DAY = HOUR * 24
export const WEEK = DAY * 7
export const MONTH = WEEK * 4
export const YEAR = DAY * 365