/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export interface HelloRequest {
    name?: string;
}
// The response message containing the greetings
export interface HelloReply {
    message?: string;
}
export interface Greeter {
    sayHello(data: HelloRequest, metadata?: Metadata): Observable<HelloReply>;
}

