/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export interface SpotPriceDto {
    symbol?: string;
    bid?: number;
    ask?: number;
    mid?: number;
    valueDate?: number;
    creationTimestamp?: number;
}

